export const usersConstants = {
    ADD_USER_REQUEST: "ADD_USER_REQUEST",
    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    EDIT_USER_REQUEST: "EDIT_USER_REQUEST",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    INIT_LOAD: 'INIT_LOAD',
    FAILURE: " FAILURE"
}